# Generated by Django 4.2.4 on 2023-08-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=300)),
                ('commentary', models.TextField(max_length=150)),
                ('is_recurring', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('normal', 'Normal'), ('lucid', 'Lucide'), ('nightmare', 'Cauchemar')], max_length=20)),
                ('mood', models.CharField(choices=[('horrible', 'Horrible'), ('unpleasant', 'Désagréable'), ('nothing_special', 'Rien de spécial'), ('rather_nice', 'Plutôt sympatique'), ('nice', 'Sympa'), ('incredible', 'Incroyable')], max_length=20)),
                ('tags', models.ManyToManyField(to='dreamapp.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
