# Generated by Django 4.2.4 on 2023-08-17 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0002_rename_dreams_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
